export const INCIDENTS_FETCH_REQUESTED = "INCIDENTS_FETCH_REQUESTED";
export const INCIDENTS_FETCH_SUCCEEDED = "INCIDENTS_FETCH_SUCCEEDED";
export const INCIDENTS_FETCH_FAILED = "INCIDENTS_FETCH_FAILED";

export const INCIDENT_FETCH_REQUESTED = "INCIDENT_FETCH_REQUESTED";
export const INCIDENT_FETCH_SUCCEEDED = "INCIDENT_FETCH_SUCCEEDED";
export const INCIDENT_FETCH_FAILED = "INCIDENT_FETCH_FAILED";

export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";