export const INCIDENTS_FETCH_REQUESTED = "INCIDENTS_FETCH_REQUESTED";
export const INCIDENTS_FETCH_SUCCEEDED = "INCIDENTS_FETCH_SUCCEEDED";
export const INCIDENTS_FETCH_FAILED = "INCIDENTS_FETCH_FAILED";

export const SET_SELECTED_INCIDENT = "SET_SELECTED_INCIDENT";